version: '3'
services:
  server:
    build ./src
    volumes:
        - .:/src
    ports:
        - "3100:3100"
    restart: always
    environment:
        - NODE_ENV=production
    command: npm start